### ISSUE TITLE
database is locked (code 5)

### ISSUE THREAD

**Issue by yuwu** [square/sqlbrite#139]
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
                                                                               at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                               at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                                               at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
                                                                               at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
                                                                               at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
                                                                               at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
                                                                               at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                               at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                               at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                               at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                               at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
                                                                               at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
                                                                               at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                               at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:988)
                                                                               at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
                                                                               at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
                                                                               at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
                                                                               at com.squareup.sqlbrite.BriteDatabase.getReadableDatabase(BriteDatabase.java:138)
                                                                               at com.squareup.sqlbrite.BriteDatabase.query(BriteDatabase.java:375)
                                                                               at blackhole.androiddesign.realm.model.RealmActivity$2.call(RealmActivity.java:57)
                                                                               at blackhole.androiddesign.realm.model.RealmActivity$2.call(RealmActivity.java:52)
                                                                               at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                                               at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                               at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                               at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                               at java.lang.Thread.run(Thread.java:841)

**Comment by JakeWharton** [comment]
What makes you think this is a SQL Brite issue?

**Comment by JakeWharton** [comment]
This exception has nothing to do with SQL Brite. It would happen if you called `getReadable()` database directly which is just what SQL Brite is doing for you.

**Comment by sarabhin18** [comment]
@JakeWharton We have also faced this issue. We haven't called getReadable() anywhere. We just simply using SqlBrite observables alone.

My crash report from Android Monitor:
`   android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
                                                                       at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                       at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                       at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
                                                                       at com.squareup.sqlbrite.BriteDatabase.insert(BriteDatabase.java:351)
                                                                       at com.hannesdorfmann.sqlbrite.dao.Dao.insert(Dao.java:243)`

This report takes me to Dao.java code and following line for your review:

` protected Observable<Long> insert(final String table, final ContentValues contentValues,
      final int conflictAlgorithm) {

    return Observable.just(db.insert(table, contentValues, conflictAlgorithm));
  }`
@yuwu Is your issue resolved ?
