### ISSUE TITLE
Unable to run sample

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/sqlbrite#157]
Steps to reproduce:
1) Clone this repo
2) Import the project in Android Studio 2.3 Canary 2
3) Run the sample

Expected result:
app should not crash

Actual result:
app crashes with
>  FATAL EXCEPTION: main
                                                                                       Process: com.example.sqlbrite.todo.development, PID: 16109
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sqlbrite.todo.development/com.example.sqlbrite.todo.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.AdapterView.setEmptyView(android.view.View)' on a null object reference
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.AdapterView.setEmptyView(android.view.View)' on a null object reference
                                                                                           at com.example.sqlbrite.todo.ui.ListsFragment.onViewCreated(ListsFragment.java:97)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1132)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                                                           at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                                           at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                                           at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                                           at android.app.Activity.performStart(Activity.java:6696)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:154)

**Comment by nextdimension** [comment]
Easy fix for now,   listView =  (ListView) view.findViewById(android.R.id.list);
Butterknife is failing to bind to the listview for some reason. Needs more investigation.

**Comment by IgorGanapolsky** [comment]
@nextdimension You are absolutely right.  That works.
