### ISSUE TITLE
delete("table", null, null) throws java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by pbochenski** [square/sqlbrite#172]
I'm trying to delete all content from table. 
using:
```
db.delete("table", null, null)
```
throws:
```
java.lang.IllegalArgumentException: Too many bind arguments.  1 arguments were provided but the statement needs 0 arguments.
                                                                at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:68)
                                                                at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1496)
                                                                at com.squareup.sqlbrite.BriteDatabase.delete(BriteDatabase.java:460)
                                                                at com.usecasetest.repository.DbRepo.saveComments(Jsonplaceholder.kt:25)
```
I'm using sqlbrite:1.1.1 and kotlin

during debuging I've found out that whereArgs in BriteDatabase.delete method is not actually null
(see screenshot: http://imgur.com/a/hu0yZ). Is it kotlin issue?

**Comment by JakeWharton** [comment]
It might be a Kotlin bug. Let me look into it later tonight.

**Comment by JakeWharton** [comment]
BTW a quick workaround is to just leave off the third argument. It's a varargs method so `db.delete("table", null)` should be enough. When you supply `null` it creates a one-element `String[]` whose sole value is a `null`.

Firing up my IDE to look at the behavior of Java vs. Kotlin when you do pass a third argument, though. I'll comment with a Kotlin bug link if they're actually different.
