### ISSUE TITLE
SQLiteDatabaseLockedException

### ISSUE THREAD

**Issue by sarabhin18** [square/sqlbrite#180]
@JakeWharton We have also faced this issue. We haven't called getReadable() anywhere. We just simply using SqlBrite observables alone. Can we have any suggestion on this issue? It'd helpful to identify the loop hole.

My crash report from Android Monitor:
`   android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
                                                                       at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                       at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                       at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                       at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
                                                                       at com.squareup.sqlbrite.BriteDatabase.insert(BriteDatabase.java:351)
                                                                       at com.hannesdorfmann.sqlbrite.dao.Dao.insert(Dao.java:243)`

This report takes me to Dao.java code and following line:

` protected Observable<Long> insert (final String table, 
                     final ContentValues contentValues, final int conflictAlgorithm) {
    return Observable.just(db.insert(table, contentValues, conflictAlgorithm));
  }`
@yuwu Is your issue resolved ?

Please refer the below issue:
https://github.com/square/sqlbrite/issues/139

**Comment by JakeWharton** [comment]
The exception comes from Sqlite, not this library which just wraps it. There's no action to take here.
