### ISSUE TITLE
Crash with rxjava 1.0.14

### ISSUE THREAD

**Issue by gabrielittner** [square/sqlbrite#41]
This is a very simplified version of what I'm doing:
```
  Observable<List<ListsItem>> lists = db.createQuery(ListsItem.TABLES, ListsItem.QUERY)       
      .map(ListsItem.MAP)
      .replay(1)
      .refCount();
  Subscription subscription = Observable.combineLatest(lists, lists, func2)
      .subscribe();
```

When using rxjava 1.0.14 it's crashing when calling `unsubscribe()` (1.0.13 works fine).

Stacktrace
```
08-21 18:29:49.980  18952-18952/com.example.sqlbrite.todo.development E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.sqlbrite.todo.development, PID: 18952
    java.lang.RuntimeException: Unable to pause activity {com.example.sqlbrite.todo.development/com.example.sqlbrite.todo.ui.MainActivity}: java.lang.IllegalArgumentException: requested -1 < 0
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3312)
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3259)
            at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3234)
            at android.app.ActivityThread.access$1000(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.IllegalArgumentException: requested -1 < 0
            at com.squareup.sqlbrite.BackpressureBufferLastOperator$BufferLastSubscriber$1.request(BackpressureBufferLastOperator.java:52)
            at rx.internal.operators.OperatorReplay$ReplaySubscriber.manageRequests(OperatorReplay.java:521)
            at rx.internal.operators.OperatorReplay$InnerProducer.unsubscribe(OperatorReplay.java:716)
            at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
            at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
            at rx.Subscriber.unsubscribe(Subscriber.java:98)
            at com.example.sqlbrite.todo.ui.ListsFragment.onPause(ListsFragment.java:141)
            at android.support.v4.app.Fragment.performPause(Fragment.java:1950)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1005)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
            at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:1943)
            at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:393)
            at android.app.Activity.performPause(Activity.java:6064)
            at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1317)
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3292)
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3259)
            at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3234)
            at android.app.ActivityThread.access$1000(ActivityThread.java:148)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

Code to try it in the SqlBrite sample: https://gist.github.com/gabrielittner/e428bd24592f194c518c/revisions

**Comment by JakeWharton** [comment]
This is an RxJava bug that is already fixed. I don't have the link handy
(mobile) but look at its recent issues if you're curious.

**Comment by gabrielittner** [comment]
Thanks. Forgot to search there.

**Comment by JakeWharton** [comment]
Just landed. Sounds like you found it, but for others and historical documentation: https://github.com/ReactiveX/RxJava/issues/3166
